export const FETCH_IMG_RESPONSE ="FETCH_IMG_RESPONSE"
export const FETCH_IMG_SUCCESS ="FETCH_IMG_SUCCESS"
export const FETCH_IMG_FAIL ="FETCH_IMG_FAIL"


export const SEARCH_IMG_RESPONSE ="SEARCH_IMG_RESPONSE"
export const SEARCH_IMG_SUCCESS ="SEARCH_IMG_SUCCESS"
export const SEARCH_IMG_FAIL ="SEARCH_IMG_FAIL"

export const LOADMORE_IMG_RESPONSE ="LOADMORE_IMG_RESPONSE"
export const LOADMORE_IMG_SUCCESS ="LOADMORE_IMG_SUCCESS"
export const LOADMORE_IMG_FAIL ="LOADMORE_IMG_FAIL"