export const FETCH_IMG_RESPONSE ="FETCH_IMG_RESPONSE"
export const FETCH_IMG_SUCCESS ="FETCH_IMG_SUCCESS"
export const FETCH_IMG_FAIL ="FETCH_IMG_FAIL"


export const SEARCH_IMG_RESPONSE ="SEARCH_IMG_RESPONSE"
export const SEARCH_IMG_SUCCESS ="SEARCH_IMG_SUCCESS"
export const SEARCH_IMG_FAIL ="SEARCH_IMG_FAIL"

export const LOADMORE_IMG_RESPONSE ="LOADMORE_IMG_RESPONSE"
export const LOADMORE_IMG_SUCCESS ="LOADMORE_IMG_SUCCESS"
export const LOADMORE_IMG_FAIL ="LOADMORE_IMG_FAIL"

export const GET_IMG_BY_ID_RESPONSE ="GET_IMG_BY_ID_RESPONSE"
export const GET_IMG_BY_ID_SUCCESS ="GET_IMG_BY_ID_SUCCESS"
export const GET_IMG_BY_ID_FAIL ="GET_IMG_BY_ID_FAIL"


export const GET_IMG_BY_TAG_RESPONSE ="GET_IMG_BY_TAG_RESPONSE"
export const GET_IMG_BY_TAG_SUCCESS ="GET_IMG_BY_TAG_SUCCESS"
export const GET_IMG_BY_TAG_FAIL ="GET_IMG_BY_TAG_FAIL"

export const LOAD_MORE_TAG_RESPONSE ="LOAD_MORE_TAG_RESPONSE"
export const LOAD_MORE_TAG_SUCCESS ="LOAD_MORE_TAG_SUCCESS"
export const LOAD_MORE_TAG_FAIL ="LOAD_MORE_TAG_FAIL"